### ISSUE TITLE
Slash in Bold and ExtraBold

### ISSUE THREAD

**Issue by Ypnose** [sharpjs/JetBrainsMonoSlashed#1]
Hi there !
I'm really happy to use your variant. For `Bold` and `Extrabold`, do you think you can increase the slash weight ?

I hope you'll also maintain it when upstream releases new versions.

**Comment by sharpjs** [comment]
Hi, and thanks for the comments!

I suggest you [open an issue in the JetBrains Mono repo](https://github.com/JetBrains/JetBrainsMono/issues) to request an increase in the slash weight.

The only thing I do to JetBrains Mono is set its `zero` and `calt` OpenType features to enabled by default, using [`pyftfeatfreeze`](https://github.com/twardoch/fonttools-opentype-feature-freezer).  I don't have the skills to modify the glyphs inside the font.

I plan to keep this variant current with upstream as long as it is useful and easy to do.  If JetBrains Mono drops the `zero` feature, I would be unable to continue updates.  If upstream release an official slashed-zero variant, I probably would discontinue updates then, too.
