### ISSUE TITLE
Can we have also a NL ttf version?

### ISSUE THREAD

**Issue by f2l2pe** [sharpjs/JetBrainsMonoSlashed#2]
I have some problems when working with OTF on windows, can we have a no ligatures ttf version too?

**Comment by sharpjs** [comment]
I'll check on that. When I tried a few months ago, I had trouble tweaking the NL version. I did not try very hard, though.  I'll give it another look!

**Comment by f2l2pe** [comment]
Thank you! :)

**Comment by sharpjs** [comment]
No-ligatures variant now included in [release 2.002](https://github.com/sharpjs/JetBrainsMonoSlashed/releases/tag/v2.002). Enjoy!
