### ISSUE TITLE
Some characters are rendered differently than the original version

### ISSUE THREAD

**Issue by jasmingrbo** [sharpjs/JetBrainsMonoSlashed#3]
e, f, J, K, % to name a few are rendered differently than the original version.

If you could investigate what's going on that would be much appreciated.

Thank you!

**Comment by sharpjs** [comment]
I'll take a look.

**Comment by sharpjs** [comment]
Currently, for reference:
![image](https://user-images.githubusercontent.com/708461/95025070-0664b600-063c-11eb-9e31-1bfd7ad0507e.png)

**Comment by sharpjs** [comment]
Without the `calt` feature, which I have been adding in addition to `zero`:
![image](https://user-images.githubusercontent.com/708461/95025202-e5e92b80-063c-11eb-9c71-1ee2f5d33e14.png)

**Comment by sharpjs** [comment]
And here's the original JetBrains Mono:
![image](https://user-images.githubusercontent.com/708461/95025303-8c353100-063d-11eb-973f-96fa394b8335.png)
Should I be seeing any differences among these?

@grb0, in what kind of environment are you seeing differences — what OS + program + rendering settings?

**Comment by jasmingrbo** [comment]
I've recorded a short video, you can watch it at: https://streamable.com/yvpxzd
The most notable difference is with f, J and % characters.
Environment: Windows 10 + AS + Subpixel

**Comment by sharpjs** [comment]
Thank you.  That is definitely noticeable.  I'll try to find some way to repro that here.

**Comment by sharpjs** [comment]
@grb0 can you check if the issue remains in [v2.200](https://github.com/sharpjs/JetBrainsMonoSlashed/releases/tag/v2.200) of both upstream and Slashed?

**Comment by jasmingrbo** [comment]
@sharpjs I've checked it against upstream v2.21, when it comes to char rendering seems to be fixed and exactly the same as the upstream. But now the line spacing is different, for example: line spacing of 1.2 for the upstream is roughly 1.3 line spacing for Slashed version.
