### ISSUE TITLE
upgrade to new jetbrains mono version v2.304

### ISSUE THREAD

**Issue by dantezhu** [sharpjs/JetBrainsMonoSlashed#5]
Jetbrains mono has released the new version v2.304, could you please upgrade to the latest version?
<img width="772" alt="image" src="https://user-images.githubusercontent.com/1105212/222386724-0a83d851-eaf1-434c-b03a-b5c7784263d4.png">

**Comment by sharpjs** [comment]
Sorry for the delay on this.  I've been meaning to do this ever since it was released.

**Comment by dantezhu** [comment]
@sharpjs Thanks a lot!🙏

**Comment by sharpjs** [comment]
[Here you go](https://github.com/sharpjs/JetBrainsMonoSlashed/releases/tag/v2.304).  Enjoy!
